# Generated by Django 6.1 on 2026-08-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='violation',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
