# Generated by Django 6.1 on 2026-08-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0002_alter_violation_description_alter_violation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='title',
        ),
        migrations.AddField(
            model_name='violation',
            name='attributed_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='المنسوب له المخالفة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='violation',
            name='committee_decision_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تاريخ إصدار قرار المخالفة من اللجنة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='منشئ المخالفة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='violation',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='violation',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='violation',
            name='notified_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تاريخ إشعار المنسوب له المخالفة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='person_response_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تاريخ رد المنسوب له المخالفة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='referral_repetition',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='تكرار الإحالة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='regulation',
            field=models.TextField(blank=True, default='', verbose_name='اسم النظام أو اللائحة المستند عليها'),
        ),
        migrations.AddField(
            model_name='violation',
            name='report_data',
            field=models.JSONField(blank=True, null=True, verbose_name='بيانات المحضر'),
        ),
        migrations.AddField(
            model_name='violation',
            name='report_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تاريخ تحرير المحضر'),
        ),
        migrations.AddField(
            model_name='violation',
            name='report_editor',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='محرر المحضر'),
        ),
        migrations.AddField(
            model_name='violation',
            name='secretariat_referral_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تاريخ إحالتها الى الأمانة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='secretariat_response_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تاريخ رد الأمانة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='sector_referral_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تاريخ إحالتها إلى القطاع المختص'),
        ),
        migrations.AddField(
            model_name='violation',
            name='sector_response_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تاريخ رد القطاع المختص'),
        ),
        migrations.AddField(
            model_name='violation',
            name='transaction_status',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='حالة المعاملة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AddField(
            model_name='violation',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_location',
            field=models.TextField(blank=True, default='', verbose_name='موقع المخالفة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='رقم المحضر'),
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_status',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='حالة المخالفة'),
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='نوع المخالفة'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء السجل'),
        ),
    ]
